// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/src/Dialog.vue')['default']
    Empty: typeof import('./src/components/src/Empty.vue')['default']
    JisNavBar: typeof import('./src/components/src/Jis-NavBar.vue')['default']
    JisTabBar: typeof import('./src/components/src/Jis-TabBar.vue')['default']
    Loading: typeof import('./src/components/src/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/src/Screen.vue')['default']
  }
}
