export default {
  '--color-body': '#1e1e1e',
  '--color-text': '#fff',
  '--color-primary': '#4a7afe',
  '--color-info': '#10afef',
  '--color-success': '#10c48f',
  '--color-warning': '#ff8800',
  '--color-danger': '#ef5350',
  '--color-disabled': '#404040',
  '--color-text-disabled': '#757575',
  '--action-sheet-background': '#1e1e1e',
  '--action-sheet-title-color': '#aaa',
  '--action-sheet-action-item-color': '#fff',
  '--app-bar-color': '#272727',
  '--badge-default-color': '#555',
  '--bottom-navigation-background-color': '#272727',
  '--bottom-navigation-border-color': '#444',
  '--bottom-navigation-item-active-background-color': '#272727',
  '--button-default-color': '#303030',
  '--card-background': '#303030',
  '--card-title-color': '#ffffff',
  '--card-subtitle-color': '#aaaaaa',
  '--card-description-color': '#aaaaaa',
  '--cell-desc-color': '#aaa',
  '--cell-border-color': '#545454',
  '--checkbox-unchecked-color': '#fff',
  '--chip-default-color': '#555',
  '--collapse-background': '#303030',
  '--collapse-text-color': '#fff',
  '--collapse-border-top': 'thin solid rgba(255, 255, 255, 0.12)',
  '--date-picker-main-color': '#fff',
  '--date-picker-body-background-color': '#303030',
  '--day-picker-head-item-color': '#aaaaaa',
  '--dialog-background': '#1e1e1e',
  '--dialog-message-color': '#bbb',
  '--divider-color': 'rgba(255, 255, 255, 0.2)',
  '--divider-text-color': '#aaa',
  '--input-input-text-color': '#fff',
  '--input-blur-color': 'rgb(255, 255, 255, .7)',
  '--pagination-list-bg-color': '#303030',
  '--pagination-hover-bg-color': '#25293a',
  '--pagination-list-active-bg-color': '#25293a',
  '--pagination-list-active-color': '#4a7afe',
  '--pagination-item-background': '#303030',
  '--picker-background': '#1e1e1e',
  '--picker-cancel-button-text-color': '#aaa',
  '--picker-picked-border': '1px solid rgba(255, 255, 255, 0.12)',
  '--picker-mask-background-image':
    'linear-gradient(180deg, hsla(0, 0%, 12%, 0.9), hsla(0, 0%, 12%, 0.4)), linear-gradient(0deg, hsla(0, 0%, 12%, 0.9), hsla(0, 0%, 12%, 0.4))',
  '--popup-content-background-color': '#1e1e1e',
  '--pull-refresh-background': '#303030',
  '--radio-unchecked-color': '#fff',
  '--select-select-text-color': '#fff',
  '--select-blur-color': 'rgb(255, 255, 255, .7)',
  '--select-scroller-background': '#303030',
  '--skeleton-card-background-color': 'hsla(0,0%,100%,.12)',
  '--skeleton-animation-background':
    'linear-gradient(\n        90deg,hsla(0,0%,100%,0),hsla(0,0%,100%,.05),hsla(0,0%,100%,0))\n      ',
  '--skeleton-avatar-background-color': 'hsla(0,0%,100%,.12)',
  '--skeleton-title-background-color': 'hsla(0,0%,100%,.12)',
  '--step-content-color': 'rgba(255, 255, 255, .38)',
  '--step-content-active-color': '#fff',
  '--step-line-background': '#fff',
  '--switch-track-background': '#727272',
  '--switch-handle-background': '#727272',
  '--tab-item-content-color': '#aaa',
  '--tab-inactive-color': 'rgba(255, 255, 255, .65)',
  '--table-background': '#272727',
  '--table-thead-th-text-color': 'rgba(255, 255, 255, 0.6)',
  '--table-tbody-tr-hover-background': '#4c4b4b',
  '--table-thead-border-bottom': 'thin solid rgba(255, 255, 255, 0.12)',
  '--table-tbody-tr-border-bottom': 'thin solid rgba(255, 255, 255, 0.12)',
  '--tabs-background': '#1e1e1e',
  '--time-picker-clock-container-background': '#545454',
  '--time-picker-body-background': '#303030',
  '--time-picker-clock-item-disable-color': '#aaaaaa',
  '--table-row-padding': '5px',
  '--uploader-action-background': '#303030',
  '--uploader-action-icon-color': '#fff',
  '--uploader-file-name-background': '#303030',
  '--uploader-file-name-color': '#aaa',
  '--uploader-file-cover-background': '#303030',

  // input文字大小
  '--input-placeholder-size': '18px',
  '--input-focus-color': '#1d60ec',
}
